print (3 < 5)
print (5<= 5)
print (10 < 5)
print ("Test equality")
print (3==3)
print("Test Strings")
print ("abc" != "Abc")
print ("5" == 5)
print("Testing swapping")
print( 10 < 5)
print (10 > 5)
